spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true
